database:
  url: postgres://root@db.${env:ORGANIZATION}:26257/postgres?&sslmode=disable
keycloak:
  url: https://auth.daato.localhost
  realm: ${kube:daato-api-keycloak-config/realm}
  clientId: ${kube:daato-api-keycloak-config/clientId}
  clientSecret: ${kube:daato-api-keycloak-config/clientSecret}
